# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Lint, Build, Test, Cover

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build-test-cover:
    name: Lint, Build, Test, Cover
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
#    - name: Lint
#      uses: github/super-linter@v4
#      env:
#        VALIDATE_ALL_CODEBASE: true
#        DEFAULT_BRANCH: "main"
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        #FILTER_REGEX_INCLUDE: src/DotNetWrappers
#        VALIDATE_CSHARP: true
#        EDITORCONFIG_FILE_NAME: ./.editorconfig

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'
        
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      working-directory: src
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/DotNetWrappers
      
    - name: Test
      run: dotnet test  --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: src/DotNetWrappers.Tests
      
    - name: Coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: src/DotNetWrappers.Tests/coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: text
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: console
        thresholds: '10 80'
